#!/bin/bash
# trying to access script parameters inside a function
#
function func7 {
    echo $[ $1 * $2 ]
}
#
if [ $# -eq 2 ]
then
    value=$(func7 $1 $2)
    echo "The result is $value"
else
    echo "Usage: test7 a b"
fi
