#!/bin/bash
# display user unformation from the system.
echo "User info for userid: $USER"
echo UID: ${UID}
echo HOME: $HOME
# for interpret the dollar sign as an actual dolor sign (not a variable)
echo "The cost of the item is \$15"
